// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA17No5phG_1h33UO5EQhj_PvtKtaoqPUE',
    appId: '1:303864233924:web:776ba09fe3dd5cfc9aee91',
    messagingSenderId: '303864233924',
    projectId: 'super-sudoku-99labs',
    authDomain: 'super-sudoku-99labs.firebaseapp.com',
    storageBucket: 'super-sudoku-99labs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG2Ta7XQG2S1qQyJ7nbiIjmS99h8VX4oI',
    appId: '1:303864233924:android:0641c9a26e8a531b9aee91',
    messagingSenderId: '303864233924',
    projectId: 'super-sudoku-99labs',
    storageBucket: 'super-sudoku-99labs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbP3yNPCQbDsqpxq48N8e0uGUyOp7Nfgo',
    appId: '1:303864233924:ios:11e210e189a807d09aee91',
    messagingSenderId: '303864233924',
    projectId: 'super-sudoku-99labs',
    storageBucket: 'super-sudoku-99labs.firebasestorage.app',
    iosBundleId: 'com.ninetyninelabs.superSudoku',
  );
}
